FROM vagrantlibvirt/vagrant-libvirt:latest
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC \
        apt-get install --assume-yes tzdata \
    && apt-get install --assume-yes python3 python3.10-venv \
    && apt-get clean \
    && python3 -m venv ~/env \
    && ~/env/bin/pip install \
        ansible==9.6.0 jmespath==1.0.1 jsonschema==4.22.0 netaddr==1.3.0
