- hosts: openshift
  tasks:
  - name: install packages
    package:
      state: present
      name:
      - docker
      - httpd-tools
      - pyOpenSSL
      - python-cryptography
      - python-lxml
  vars:
  tasks:
  - name: generate random password for user
    shell:
      cmd: tr -cd A-Za-z0-9 < /dev/urandom | head -c 30
      creates: '{{ openshift_secrets_dir }}/user.pwd'
    register: pw
  - name: create password file
    shell:
      cmd: echo '{{ pw.stdout }}' > '{{ openshift_secrets_dir }}/user.pwd'
      creates: '{{ openshift_secrets_dir }}/user.pwd'
  - name: create htpasswd file
    shell:
      cmd: >
        htpasswd -ic '{{ openshift_secrets_dir }}/htpasswd'
        '{{ openshift_username }}'
        < '{{ openshift_secrets_dir }}/user.pwd'
      creates: '{{ openshift_secrets_dir }}/htpasswd'
- hosts: openshift_digitalocean
  tasks:
  - name: remove hostname -> localhost entries in /etc/hosts
    lineinfile:
      state: present
      backrefs: true
      dest: /etc/hosts
      line: '#\1'
      regexp: '^((127\.0\.0\.1|::1)\s+{{ ansible_fqdn }}.*)$'
