set nocompatible

set textwidth=80 expandtab tabstop=4 shiftwidth=0 foldminlines=0 scrolloff=0
set autoindent nostartofline
set backspace=indent,eol,start cpoptions+=$ formatoptions-=o,r
set fillchars= laststatus=1 noruler showcmd tabpagemax=100

set hidden key= lazyredraw noequalalways visualbell
set wildmenu wildmode=longest:full,full
set hlsearch ignorecase incsearch smartcase
set grepprg=rg\ --vimgrep\ $*

filetype on
filetype plugin on
filetype indent on
