- hosts: desktops:&arch
  become: yes
  tasks:
  - name: enable for console logins
    blockinfile:
      state: present
      dest: /etc/pam.d/system-local-login
      block: |
        auth     optional  pam_gnupg.so store-only
        session  optional  pam_gnupg.so
  - name: enable for i3lock
    lineinfile:
      state: present
      dest: /etc/pam.d/i3lock
      line: auth     optional  pam_gnupg.so
- hosts: desktops:&arch
  vars:
    home: "{{ ansible_env.HOME }}"
  tasks:
  - name: enable gpg-preset-passphrase
    lineinfile:
      path: "{{ home }}/.gnupg/gpg-agent.conf"
      line: allow-preset-passphrase
      create: true
  - name: populate pam-gnupg key ID file
    copy:
      dest: "{{ home }}/.config/pam-gnupg"
      # $ gpg2 --list-secret-keys --with-keygrip
      content: |
        2E2E172E019FB7185972C20A9EC30C06B7645832
