- hosts: desktops:&arch
  vars:
    home: "{{ ansible_env.HOME }}"
  tasks:
  - name: enable gpg-preset-passphrase
    lineinfile:
      path: "{{ home }}/.gnupg/gpg-agent.conf"
      line: allow-preset-passphrase
      create: true
  - name: populate pam-gnupg key ID file
    copy:
      dest: "{{ home }}/.config/pam-gnupg"
      # $ gpg2 --list-secret-keys --with-keygrip
      content: |
        2E2E172E019FB7185972C20A9EC30C06B7645832
