- hosts: desktops:&arch
  tasks:
  - name: enable for console logins
    blockinfile:
      state: present
      dest: /etc/pam.d/system-local-login
      block: |
        auth     optional  pam_gnupg.so store-only
        session  optional  pam_gnupg.so
  - name: enable for i3lock
    lineinfile:
      state: present
      dest: /etc/pam.d/i3lock
      line: auth     optional  pam_gnupg.so
