- hosts: desktops
  vars:
    home: "{{ ansible_env.HOME }}"
    nixpkgs: https://nixos.org/channels/nix-22.05
  tasks:
  - fail:
      msg: >
        `nixpkgs` is required, choose the appropriate URL from
        https://channels.nixos.org (e.g. https://nixos.org/channels/nixos-22.05)
    when: nixpkgs is undefined
  - name: add channel
    command:
      argv:
      - nix-channel
      - --add
      - "{{ nixpkgs }}"
      - nixpkgs
      creates: "{{ home }}/.nix-channels"
  - name: update channel information
    command:
      argv:
      - nix-channel
      - --update
      creates: "{{ home }}/.nix-channels"
