- hosts: desktops
  vars:
    home: "{{ ansible_env.HOME }}"
    profile_path: "{{ home }}/.nix-profile"
  tasks:
  - fail:
      msg: >
        `nixpkgs` is required, choose the appropriate URL from
        https://channels.nixos.org
    when: nixpkgs is undefined
  - name: add channel
    command:
      argv:
      - nix-channel
      - --add
      - "{{ nixpkgs }}"
      - nixpkgs
      creates: "{{ home }}/.nix-channels"
  - name: update channel information
    command:
      argv:
      - nix-channel
      - --update
      creates: "{{ home }}/.nix-channels"
