- hosts: bbb
  tasks:
  - name: configure locale
    locale_gen:
      name: en_US.UTF-8
      state: present
  - name: create locale.conf
    copy:
      dest: /etc/locale.conf
      content: |
        LANG=en_US.UTF-8
