- hosts: all
  tasks:
  - name: add udev rule
    copy:
      dest: /etc/udev/rules.d/backlight.rules
      owner: root
      group: root
      mode: 0440
      content: |
        ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chgrp video /sys/class/backlight/intel_backlight/brightness"
        ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chmod g+w /sys/class/backlight/intel_backlight/brightness"
