# Pre-requisites (must be done manually):
# - Password-less ssh access.
# - (Optional, but helpful) configure mirrors.
# - # pacman-key --init
# - # pacman-key --populate archlinuxarm
# - # pacman -Syyu python
# Repurpose the `alarm` user, which has UID 1000 (base.yaml would fail to add
# the default user otherwise):
# - # usermod --login bbguimaraes --home /home/bbguimaraes alarm
# - # mv /home/alarm ~bbguimaraes
# With that done, execute the base.yaml playbook, then this one.
- hosts: all
  tasks:
  - name: configure locale
    locale_gen:
      name: en_US.UTF-8
      state: present
