# If not running interactively, don't do anything
[[ $- != *i* ]] && return
[[ -f /etc/bash.bashrc ]] && . /etc/bash.bashrc
[[ -f /etc/bashrc ]] && . /etc/bashrc

eval "$(dircolors)"
alias ls='ls --color=auto'
PS1='$ '
complete -C 'd completion' d

. /usr/share/fzf/completion.bash
. /usr/share/fzf/key-bindings.bash

function d() {
    [[ "$#" -eq 0 ]] && exec d
    case "$1" in
    cd) shift; eval "$(command d cd "$@")"; cd "$@";;
    *) command d "$@";;
    esac
}
